export const languages: string[] = [
    "Hindi",
    "Tamil",
    "Telugu",
    "Kannada",
    "Malayalam",
    "Marathi",
    "English",
    "Mandarin Chinese",
    "Spanish",
    "French",
    "Arabic",
    "Russian",
    "Portuguese",
    "German",
    "Japanese",
    "Korean",
    "Turkish",
    "Italian", 
];
